### ISSUE TITLE
"Previous image", "Next image", "Play track" is unavailable.

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [openstreetcam/josm-plugin#24]
Open track, press edit (https://openstreetcam.org/details/1274477/59/edit-osm) -> josm.

JOSM shows 5 poins and photo.

"Previous image", "Next image", "Play track" is disabled.

![screenshot](https://user-images.githubusercontent.com/14617699/44425478-a5c9aa80-a594-11e8-8304-c32ed19ff1c1.png)

**Comment by beataj-telenav** [comment]
The Previous image, Next Image and Play Track buttons are available only if also the track corresponding to the selected photo is displayed. In your case only the selected photo is displayed.
In order to display the track coresponding to a selected photo, you need to enable the "Load track on image selection" option from the OSC plugin preference settings:
![screen shot 2018-08-30 at 3 47 37 pm](https://user-images.githubusercontent.com/13517512/44852551-3460ba80-ac6c-11e8-9c0c-9c90e048e520.png)

**Comment by c-e-p-x-u-o** [comment]
Thank you!

1. Could you make it default setting. (Set "Load track on image selection" by default)
2. Add more brief description what this setting does and may be add floating bubble to the disabled next-previous buttons to suggest enable this checkbox.

**Comment by c-e-p-x-u-o** [comment]
OK, I've enabled "Load track on image selection". Thank you! Now I can use next-play-previous buttons.

But new images are not shown on the map as dots.


Open track, press edit (https://openstreetcam.org/details/1274477/59/edit-osm) -> josm.
Pres the fourth photo (plugin loads the track and show it):
![1](https://user-images.githubusercontent.com/14617699/44853471-beaa1e00-ac6e-11e8-9565-8144dae18697.png)

press next, and it loads next photo and selects next blue marker:
![2](https://user-images.githubusercontent.com/14617699/44853484-c36ed200-ac6e-11e8-91c9-c593b7805809.png)

press next, and it loads next photo but NO blue marker selected:
![3](https://user-images.githubusercontent.com/14617699/44853487-c669c280-ac6e-11e8-8970-c557f821fd1e.png)

Is this a separate bug?
